### ISSUE TITLE
Change JS for voting an idea to Coffee and KO

### ISSUE THREAD

**Issue by amirci** [winnipegrb/winnivote#10]
Instead of using javascript in the index slim file to vote an idea let's switch to **knockout.js** and **coffeescript** to write the viewmodels

**Comment by gmcgibbon** [comment]
What is the best way of getting the initial values of data-bound elements? Should I get them from the page's DOM or can I inject view logic somehow? 

Also, should I create view model classes per page, per section, or both?

**Comment by amirci** [comment]
Not sure what you mean... what are you trying to do?

**Comment by gmcgibbon** [comment]
I have a CoffeeScript class:

``` coffeescript
class KOModel.Idea
    constructor (title, description, vote_count, upvote) ->
        @title        = ko.observable(title)
        @description  = ko.observable(description)
        @vote_count   = ko.observable(vote_count)
        @upvote       = ko.observable(upvote)
```

I am wondering what the best way of getting initial values for each idea would be. When I call ko.applyBindings(new KOModel.Idea(_values_)) to bind nodes I need _values_ as they appear in the database. I can get these through the DOM when the page is loaded but I was curious if directly passing variables from the view is possible. 
Some places claim appending .erb to the end of the file runs it through rails first which would make sense. I will give that a shot and see what happens.

**Comment by gmcgibbon** [comment]
Maybe [one](http://railscasts.com/episodes/324-passing-data-to-javascript) [of](http://stackoverflow.com/questions/15028243/rails-haml-passing-data-to-javascript) [these](http://stackoverflow.com/questions/8108511/how-to-access-instance-variables-in-coffeescript-engine-inside-a-slim-template) will clarify the issue further. Since I would be writing inline JS for each idea listed it would be cleaner to use the DOM. Keeping JavaScript/CoffeeScript in separate files just makes more sense to me anyway.

**Comment by amirci** [comment]
Put a coffee file with:

``` coffeescript
window.WinniVote = {}
```

Then on the slim file:

``` slim
javascript:
   window.ideas = #{raw @ideas.to_json }

coffeescript:
   ko.appplyBindings new WinniVote.IdeasViewModel(ideas)
```

And finally the view model (using KO mapping):

``` coffeescript
class WinniVote.IdeasViewModel
  constructor: (json_ideas) ->
      @ideas = (new Idea(i) for i in json_ideas)

class WinniVote.Idea
  constructor: (json) ->
    ko.mapping.fromJS(i, {}, this)
```

**Comment by gmcgibbon** [comment]
I've got a weird issue where the page's elements aren't being updated. I can see the ajax request complete so it must be something to do with KO. Any ideas? 76457df60a2525c335c198c0adbd734fbb10ef97

**Comment by amirci** [comment]
Please push the branch to your repo and I'll take a look

**Comment by gmcgibbon** [comment]
It should be already, see the CoffeeScript [here](https://github.com/gmcgibbon/winnivote/tree/f10_change_js_for_voting_an_idea_to_coffee_and_ko/app/assets/javascripts) and the view [here](https://github.com/gmcgibbon/winnivote/tree/f10_change_js_for_voting_an_idea_to_coffee_and_ko/app/views/ideas). I think there's something wrong with this branch, git was acting funny when I pushed it to remote. Let me know if you experience any issues.

**Comment by amirci** [comment]
Please, rebase with the latest changes and push again.

**Comment by gmcgibbon** [comment]
Long story short my forked master was completely broken. I reforked and everything is well (I hope). This changes a few things in the view however so I pushed up only my CoffeeScript classes for starters. I was using a foreach bind that worked before but now that the idea markup is a partial I have to refactor. 0ec992c8caed8550b51e4bdf57764dafffb73b60

**Comment by amirci** [comment]
Suggestions & Comments:
- Create a Views folder under Javascripts and put all the ViewModel classes there
- Create a Model folder under Javascripts and put all the models there 
- When coding in JS use the JS notation, for example _ideasJson_ instead of _ideas_json_
- The _foreach_ data bind should be just _ideas_ no need _as_ etc....

```
ul data-bind="foreach: ideas"
```
- Not sure why you are using _@json_ to access the fields after you did the mapping.

Let me know when you have a work(ish) version and I'll review it.

**Comment by gmcgibbon** [comment]
Well this is embarrassing, most issues were caused by a deprecated knockout gem with an ancient version of KO. I now need to filter out idea duplicates caused by the foreach KO loop and rails partial renders. Idea observables seem to bind to both list node copies, what is the best way of fixing this? 
65450468590a2be753b05f7208cf4a6962fc1cbb

**Comment by amirci** [comment]
Not sure what you mean with both nodes. 

However I changed the code fe86990 to use only JS to populate and manipulate the ideas and edit inline. In this case you pass the information to the view model and that would populate the ideas.

Please take my branch and work from there.

**Comment by gmcgibbon** [comment]
You seem to have gone ahead and done most of the work. The requirement has been met and the tests pass on your branch. What is left to do for this feature?

**Comment by amirci** [comment]
I think you are right, I got carried away a bit..... :$

Why not add a small Jasmine test? So it serves as example....

**Comment by gmcgibbon** [comment]
Another thing I've never done. I'll look into it. Should I commit these changes to a #10 branch or make a new branch for #45?

**Comment by amirci** [comment]
I'll merge this branch and create another for #45 so you can work on it
