### ISSUE TITLE
Implement page objects for features

### ISSUE THREAD

**Issue by amirci** [winnipegrb/winnivote#15]
Page objects will help us abstract the page implementation from the tests and make tests easy to understand and modify

**Comment by gmcgibbon** [comment]
Has anyone started this? If not, how might I start on page objects?

**Comment by swalberg** [comment]
I was looking at this one yesterday as I wasn't familiar with it.

http://martinfowler.com/bliki/PageObject.html explains the pattern

http://techblog.constantcontact.com/software-development/keeping-it-dry-with-page-objects/ is an example of using [site_prism](https://github.com/natritmeyer/site_prism), which looks like a decent gem to use.

IMHO a good PR for this would implement whatever config is necessary to get the page objects integrated into the test suite, and simplifies one of the feature specs to use it.

**Comment by dbernar1** [comment]
Looks pretty solid. Thanks for the links.

**Comment by gmcgibbon** [comment]
Interesting, I can see how this will greatly simplify Capybara tests. I will start a new branch attempting this implementation tomorrow.

**Comment by swalberg** [comment]
Feel free to push up your work in progress for feedback as you go, or bring up questions in the issue or on #winnipegrb. I'm eager to see what you come up with.

**Comment by gmcgibbon** [comment]
Just so everyone is on the same page, the way I am structuring this is as follows (with the help of site_prism):
- A Page has Sections
- A Section has Elements (identified by a parent selector for reusability and child Element selector scope)
- An Element contains a CSS selector for a certain node

Pages can also contain Elements but we should only do this if the Element does not belong in a Section. The current structure of selectors do not make implementing this easy so adding IDs to Section parent nodes is needed. Are these selector adjustments another issue or should I do this too? Converting the existing tests to this methodology is a consideration as well.

The way I see it, Pages should look something like this:

``` ruby
class Home < SitePrism::Page
  set_url root_url

  section :user_nav, UserNav, "#user_nav_selector"
  section :notification, Notification, "#notification_selector"
  section :ideas, IdeasList, "#ideas_selector"
end
```

More code examples [here](http://rdoc.info/gems/site_prism/frames).

**Comment by amirci** [comment]
Looks good.

Following what Sean said, I would use one of the simplest acceptance test to drive/guide the page object implementation, that way we can be sure that we are implementing the minimum necessary in order to make it work.

The we can create more PR and keep extending the page object model.

For example, list_ideas_spec looks like a good candidate to start.

**Comment by gmcgibbon** [comment]
I rewrote list_ideas_spec to use page models: eef4b33e0880958a610a39bbcc727b3a66b8a695 It passes but I am still learning RSpec so let me know if I should make any adjustments.

**Comment by amirci** [comment]
I just left a comment on your commit, let me know if you have any questions.

**Comment by gmcgibbon** [comment]
Adjustments made: 161214070ac9fd89b0b73e2ab3e566c49ca9d909 Is there a way to add hash creating helpers to FactoryGirl like I used in my IdeasList class?

**Comment by amirci** [comment]
Not sure what you mean, but you can pass a hash to the FactoryGirl create/build method to override the attributes if you want.

BTW the _let_ that needs **!** is the one that creates the ideas the other one can be lazy.

Also I would split up the page objects to different files.

**Comment by gmcgibbon** [comment]
I was just wondering if you can specify the values you want from the database objects returned by FactoryGirl instead of manually creating a hash in the expected let block. 

Something like: 

``` ruby
let!(:expected) do
  FactoryGirl.create_list(:idea, 10, only: [:title, :description])
end
```

It doesn't really matter, I just think it would make more sense because I hid the other hash creation.
I'm thinking of creating individual files per Page and one for all Sections. If the project ends up with a lot of Sections, we may want to sort them into separate files later on.

**Comment by amirci** [comment]
The things is that when u use _FactoryGirl_ you get instances of classes, like _Idea_.

Here you just have attributes to compare and some times not even all of them based on what you are showing on the page.
