### ISSUE TITLE
Anonymous users can't view the list of ideas

### ISSUE THREAD

**Issue by swalberg** [winnipegrb/winnivote#29]
I thought that logins were reserved for creating ideas (and possibly voting, wasn't clear on that)

_To reproduce_
As an anonymous user, view the index page (/)

_Expected behaviour_
I should see a list of ideas

_Actual behaviour_
I am prompted to log in

**Comment by dbernar1** [comment]
This seems to be a duplicate of https://github.com/winnipegrb/winnivote/issues/16

**Comment by swalberg** [comment]
You are right, sir, and #31 fixes it, thanks.
