### ISSUE TITLE
Add Jasmine tests for IdeaViewModel

### ISSUE THREAD

**Issue by amirci** [winnipegrb/winnivote#45]
Similar to ruby code we should use test first for our view models and models as well

**Comment by gmcgibbon** [comment]
Two problems I've ran into:

How can I use test database objects with Jasmine? Similar to how we use FactoryGirl and a test DB environment for our feature tests.
How can I wait for an ajax request to complete before doing the test assertion? I've tried implementing solutions using waitsFor and runs with no success.

See 0f679ea5226bb5c04eecbb34a476e6b76a4e99fe where I try to implement a test for Idea upvoting. I'm using a .slim fixture to import rails variables which may also need to be adjusted. Also be advised that because tests don't run in a test environment they change live data.

**Comment by amirci** [comment]
I pushed #45 with the basic setup and tests for the Idea JS model, please look at it.

I'm not sure what you mean with database objects, however the AJAX requests can be done using **spies**. Please look at the test I wrote.

You don't need to import rails variables you just create the JSON model you want to test. Remember is a unit test so we need to mock all other collaborating classes.

**Comment by gmcgibbon** [comment]
I see. We don't need ActiveRecord objects because we are using mock data. That spyOn function fixes the issues I was concerned with regarding mock data in Ajax calls anyway. I'll look at writing specs for the view model classes since you've already done Idea. Thanks!

**Comment by gmcgibbon** [comment]
IdeaViewModel extends Idea. How would I handle testing the presence of inheritance with Jasmine?

I am very interested to hear a response on this. Our unit test subjects are CoffeeScript classes but Jasmine is testing what it compiles down to in JS. I can't see an example of this online so perhaps it isn't possible. I need to look further into how JavaScript's object model works.

**Comment by amirci** [comment]
You don't need to test the inheritance, however if you would you just need to repeat the tests that works for Idea.

Focus on the behaviour that IdeaViewModel has without considering that is inheritance because implementation could change.

**Comment by gmcgibbon** [comment]
toggleEditing manipulates DOM events. In order to test this function and all functions that call it, I should use a fixture to load mock idea markup right? If so, is knockout binding the fixture needed as well?

**Comment by amirci** [comment]
I suggest to write the tests that don't involve the DOM or just mock the calls to manipulate the DOM

**Comment by gmcgibbon** [comment]
Done.. I think. fcc667e1169b2f73495fcd11e293ad386cf4d089

Look at the toggleEditing test and make sure it works as it should.

**Comment by gmcgibbon** [comment]
I cherry-picked the valid commits. Before I do another PR is [this](https://github.com/gmcgibbon/winnivote/commits/f45_add_jasmine_tests_for_idea_view_model_reduced) ok?
