### ISSUE TITLE
Fix tests to be more clear

### ISSUE THREAD

**Issue by amirci** [winnipegrb/winnivote#7]
Test should be refactored to  be more _descriptive_ and _clear_

**Comment by dbernar1** [comment]
I believe you had opened this issue based on the discussion we had after you wrote the first feature for the project. A discussion I initiated. Please let me know if that's not the case.

I have now elaborated on my idea for how to make the tests be more descriptive and clear through the code in this pull request: https://github.com/winnipegrb/winnivote/pull/28 . My first comment, and some of the discussion in pull request https://github.com/winnipegrb/winnivote/pull/25 also deals with this topic.

If you perceive that the way I've adjusted the tests is a good way to go forward, I can offer to adjust the rest of the existing tests in the same fashion, or we can ask for volunteers. Maybe others would like to get some practice with this.

If you already see issues with how I've implemented those tests, please let me know. I'd appreciate the opportunity to learn how to write better tests.

**Comment by amirci** [comment]
I think we can rewrite it using page objects to make it more clear. See #15
